<?php

define("CMSPATH_CORE", PATH_TO_ROOT . '');
define("CMSPATH_MAIN", dirname(__FILE__) . DIRECTORY_SEPARATOR);

define("CMSPATH_CONF", CMSPATH_MAIN . "conf" . DIRECTORY_SEPARATOR);

define("CMSPATH_BIN", CMSPATH_CORE . "bin" . DIRECTORY_SEPARATOR);
define("CMSPATH_MOD_READ", CMSPATH_CORE . "bin" . DIRECTORY_SEPARATOR . "read" . DIRECTORY_SEPARATOR);
define("CMSPATH_MOD_WRITE", CMSPATH_CORE . "bin" . DIRECTORY_SEPARATOR . "write" . DIRECTORY_SEPARATOR);
define("CMSPATH_MOD_CRON", CMSPATH_CORE . "bin" . DIRECTORY_SEPARATOR . "cron" . DIRECTORY_SEPARATOR);
define("CMSPATH_MOD_JS", CMSPATH_CORE . "bin" . DIRECTORY_SEPARATOR . "js" . DIRECTORY_SEPARATOR);
define("CMSPATH_LIB", CMSPATH_CORE . "bin" . DIRECTORY_SEPARATOR . "lib" . DIRECTORY_SEPARATOR);
define("CMSPATH_XSLT", CMSPATH_CORE . "xslt" . DIRECTORY_SEPARATOR);

define("CMSPATH_PBIN", CMSPATH_MAIN . "pbin" . DIRECTORY_SEPARATOR);
define("CMSPATH_PMOD_READ", CMSPATH_MAIN . "pbin" . DIRECTORY_SEPARATOR . "read" . DIRECTORY_SEPARATOR);
define("CMSPATH_PMOD_WRITE", CMSPATH_MAIN . "pbin" . DIRECTORY_SEPARATOR . "write" . DIRECTORY_SEPARATOR);
define("CMSPATH_PMOD_CRON", CMSPATH_MAIN . "pbin" . DIRECTORY_SEPARATOR . "cron" . DIRECTORY_SEPARATOR);
define("CMSPATH_PMOD_JS", CMSPATH_MAIN . "pbin" . DIRECTORY_SEPARATOR . "js" . DIRECTORY_SEPARATOR);
define("CMSPATH_PLIB", CMSPATH_MAIN . "pbin" . DIRECTORY_SEPARATOR . "lib" . DIRECTORY_SEPARATOR);
define("CMSPATH_PXSLT", CMSPATH_MAIN . "pxslt" . DIRECTORY_SEPARATOR);

define("CMSPATH_CSS", "css/");
define("CMSPATH_JSCORE", "jscore/");

define("CMSPATH_LOG", CMSPATH_MAIN . "log" . DIRECTORY_SEPARATOR);
define("CMSPATH_LOG_CRON", CMSPATH_MAIN . "log" . DIRECTORY_SEPARATOR . "cron" . DIRECTORY_SEPARATOR);

define("CMSPATH_CACHE_XML", CMSPATH_MAIN . "cache" . DIRECTORY_SEPARATOR . "xml" . DIRECTORY_SEPARATOR);
define("CMSPATH_CACHE_XSLT", CMSPATH_MAIN . "cache" . DIRECTORY_SEPARATOR . "xslt" . DIRECTORY_SEPARATOR);
define("CMSPATH_CACHE_CSS", CMSPATH_MAIN . "cache" . DIRECTORY_SEPARATOR . "css" . DIRECTORY_SEPARATOR);

define("CMSPATH_UPLOAD", CMSPATH_MAIN . "upload/");
define("CMSPATH_WYSWIG", CMSPATH_MAIN . "wyswyg/");
define("CMSPATH_THUMBS", CMSPATH_MAIN . "tmb/");

define('PATH_TO_EXCEL', CMSPATH_LIB . 'excel' . DIRECTORY_SEPARATOR);

?>
